[2025-08-05T23:18:19.916+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.Updatefactsales manual__2025-08-05T23:18:00.150544+00:00 [queued]>
[2025-08-05T23:18:19.969+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.Updatefactsales manual__2025-08-05T23:18:00.150544+00:00 [queued]>
[2025-08-05T23:18:19.971+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T23:18:20.042+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Updatefactsales> on 2025-08-05 23:18:00.150544+00:00
[2025-08-05T23:18:20.068+0000] {standard_task_runner.py:60} INFO - Started process 3141 to run task
[2025-08-05T23:18:20.081+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'Updatefactsales', 'manual__2025-08-05T23:18:00.150544+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmputuy67o0']
[2025-08-05T23:18:20.090+0000] {standard_task_runner.py:88} INFO - Job 213: Subtask Updatefactsales
[2025-08-05T23:18:20.270+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.Updatefactsales manual__2025-08-05T23:18:00.150544+00:00 [running]> on host 019b67754667
[2025-08-05T23:18:20.620+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='Updatefactsales' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T23:18:00.150544+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T23:18:00.150544+00:00'
[2025-08-05T23:18:22.538+0000] {_client.py:1038} INFO - HTTP Request: GET https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/StgLogs?select=last_id&table_name=eq.factsales "HTTP/2 200 OK"
[2025-08-05T23:18:22.637+0000] {logging_mixin.py:188} INFO - 
 ---------------NO HAY DATOS NUEVOS PARA INSERTAR EN SUPABASE-----------------
[2025-08-05T23:18:22.644+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-05T23:18:22.677+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Ejercicio1, task_id=Updatefactsales, execution_date=20250805T231800, start_date=20250805T231819, end_date=20250805T231822
[2025-08-05T23:18:22.751+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-05T23:18:22.843+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
