[2025-08-05T19:29:33.985+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetfactsales manual__2025-08-05T19:29:16.721170+00:00 [queued]>
[2025-08-05T19:29:34.083+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.LoadAndSetfactsales manual__2025-08-05T19:29:16.721170+00:00 [queued]>
[2025-08-05T19:29:34.103+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-05T19:29:35.537+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): LoadAndSetfactsales> on 2025-08-05 19:29:16.721170+00:00
[2025-08-05T19:29:35.672+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'LoadAndSetfactsales', 'manual__2025-08-05T19:29:16.721170+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpgcq88c75']
[2025-08-05T19:29:35.621+0000] {standard_task_runner.py:60} INFO - Started process 1161 to run task
[2025-08-05T19:29:35.823+0000] {standard_task_runner.py:88} INFO - Job 147: Subtask LoadAndSetfactsales
[2025-08-05T19:29:38.157+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.LoadAndSetfactsales manual__2025-08-05T19:29:16.721170+00:00 [running]> on host 019b67754667
[2025-08-05T19:29:41.285+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='LoadAndSetfactsales' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T19:29:16.721170+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T19:29:16.721170+00:00'
[2025-08-05T19:29:41.940+0000] {logging_mixin.py:188} INFO -    Salesid  Dateid  Productid  Segmentid  Price_PerUnit  QuantitySold
0    S1001       1       1001         19         299.99             3
1    S1002       2       1002         21          89.99            10
2    S1003       3       1003         31        1249.99             2
3    S1004       4       1004         32           5.99            40
4    S1005       5       1005         40         499.99             1
5    S1006       6       1006         43          20.00             5
6    S1007       7       1007         44          15.99            12
7    S1008       8       1008         46         120.00             7
8    S1009       9       1009         47          30.00            15
9    S1010      10       1010         48          65.50             4
10   S1011      11       1011         57          12.99            20
11   S1012      12       1012         71          45.00             8
12   S1013      13       1013         77         250.00             3
13   S1014      14       1014         81          35.00             6
14   S1015      15       1015         82          18.50             9
15   S1016      16       1001         83         299.99             2
16   S1017      17       1002         84          89.99            15
17   S1018      18       1003         86        1249.99             1
18   S1019      19       1004         97           5.99            35
19   S1020      20       1005         19         499.99             4
20   S1021      21       1006         21          20.00             6
21   S1022      22       1007         31          15.99            11
22   S1023      23       1008         32         120.00             5
23   S1024      24       1009         40          30.00            14
24   S1025      25       1010         43          65.50             7
[2025-08-05T19:29:41.945+0000] {logging_mixin.py:188} INFO - 
 ---------------SE ENCONTRAROS DATOS PARA LA CARGA INICIAL | ULTIMO ID DE LA TABLA:S1025-----------------
[2025-08-05T19:29:44.064+0000] {_client.py:1038} INFO - HTTP Request: POST https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/factsales?columns=%22Productid%22%2C%22QuantitySold%22%2C%22Dateid%22%2C%22Segmentid%22%2C%22Salesid%22%2C%22Price_PerUnit%22 "HTTP/2 400 Bad Request"
[2025-08-05T19:29:44.072+0000] {logging_mixin.py:188} INFO - Error insertando en factsales: {'code': 'PGRST204', 'details': None, 'hint': None, 'message': "Could not find the 'Dateid' column of 'factsales' in the schema cache"}
[2025-08-05T19:29:44.298+0000] {_client.py:1038} INFO - HTTP Request: POST https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/factsales?columns=%22Productid%22%2C%22QuantitySold%22%2C%22Dateid%22%2C%22Segmentid%22%2C%22Salesid%22%2C%22Price_PerUnit%22 "HTTP/2 400 Bad Request"
[2025-08-05T19:29:44.302+0000] {logging_mixin.py:188} INFO - Error insertando en factsales: {'code': 'PGRST204', 'details': None, 'hint': None, 'message': "Could not find the 'Dateid' column of 'factsales' in the schema cache"}
[2025-08-05T19:29:44.541+0000] {_client.py:1038} INFO - HTTP Request: POST https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/factsales?columns=%22Productid%22%2C%22QuantitySold%22%2C%22Dateid%22%2C%22Segmentid%22%2C%22Salesid%22%2C%22Price_PerUnit%22 "HTTP/2 400 Bad Request"
[2025-08-05T19:29:44.545+0000] {logging_mixin.py:188} INFO - Error insertando en factsales: {'code': 'PGRST204', 'details': None, 'hint': None, 'message': "Could not find the 'Dateid' column of 'factsales' in the schema cache"}
[2025-08-05T19:29:45.289+0000] {_client.py:1038} INFO - HTTP Request: PATCH https://qwpzsjaaxuijmqodvslf.supabase.co/rest/v1/StgLogs?table_name=eq.factsales "HTTP/2 200 OK"
[2025-08-05T19:29:45.323+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-08-05T19:29:45.364+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=Ejercicio1, task_id=LoadAndSetfactsales, execution_date=20250805T192916, start_date=20250805T192933, end_date=20250805T192945
[2025-08-05T19:29:45.500+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-05T19:29:45.579+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
