[2025-08-05T15:53:37.820+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Ejercicio1.CargaInicial manual__2025-08-05T15:48:20.290536+00:00 [queued]>
[2025-08-05T15:53:37.834+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Ejercicio1.CargaInicial manual__2025-08-05T15:48:20.290536+00:00 [queued]>
[2025-08-05T15:53:37.835+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-08-05T15:53:37.858+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): CargaInicial> on 2025-08-05 15:48:20.290536+00:00
[2025-08-05T15:53:37.868+0000] {standard_task_runner.py:60} INFO - Started process 256 to run task
[2025-08-05T15:53:37.875+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Ejercicio1', 'CargaInicial', 'manual__2025-08-05T15:48:20.290536+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/ejercicio1.py', '--cfg-path', '/tmp/tmpzjuxz3r9']
[2025-08-05T15:53:37.879+0000] {standard_task_runner.py:88} INFO - Job 85: Subtask CargaInicial
[2025-08-05T15:53:37.957+0000] {task_command.py:423} INFO - Running <TaskInstance: Ejercicio1.CargaInicial manual__2025-08-05T15:48:20.290536+00:00 [running]> on host 019b67754667
[2025-08-05T15:53:38.092+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Ejercicio1' AIRFLOW_CTX_TASK_ID='CargaInicial' AIRFLOW_CTX_EXECUTION_DATE='2025-08-05T15:48:20.290536+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-05T15:48:20.290536+00:00'
[2025-08-05T15:53:38.106+0000] {logging_mixin.py:188} INFO - -------------------------TABLES------------------
[2025-08-05T15:53:38.106+0000] {logging_mixin.py:188} INFO - --dimcustomersegment---
[2025-08-05T15:53:38.107+0000] {logging_mixin.py:188} INFO - --dimdate---
[2025-08-05T15:53:38.108+0000] {logging_mixin.py:188} INFO - --dimproduct---
[2025-08-05T15:53:38.108+0000] {logging_mixin.py:188} INFO - --factsales---
[2025-08-05T15:53:38.109+0000] {logging_mixin.py:188} INFO - TABLAS PRECARGADAS
[2025-08-05T15:53:38.110+0000] {python.py:201} INFO - Done. Returned value was: cargaincremental
[2025-08-05T15:53:38.111+0000] {branch.py:35} INFO - Branch into cargaincremental
[2025-08-05T15:53:38.111+0000] {skipmixin.py:178} INFO - Following branch cargaincremental
[2025-08-05T15:53:38.133+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 233, in execute
    return self.do_branch(context, super().execute(context))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/branch.py", line 36, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/skipmixin.py", line 213, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargaincremental'}.
[2025-08-05T15:53:38.140+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=Ejercicio1, task_id=CargaInicial, execution_date=20250805T154820, start_date=20250805T155337, end_date=20250805T155338
[2025-08-05T15:53:38.163+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 85 for task CargaInicial ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'cargaincremental'}.; 256)
[2025-08-05T15:53:38.212+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-05T15:53:38.269+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
